const products = [
  {
    id: 1,
    title: "iPhone 17 Pro",
    price: 999,
    rating: 4.8,
    reviews: 120,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShDi8mZmnC_EwWAlQ_ZvlZKWHdhwdj1dMW_0Oaqb2qzwFBdPLKuorUZK4&s=10",
  },
  {
    id: 2,
    title: "Nike Air Max 270",
    price: 159,
    rating: 4.6,
    reviews: 89,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSRQ5Mz0fk6DB_6cOx0OEl4xsrzBUNgNV59SX1EeF3BQ&s=10",
  },
  {
    id: 3,
    title: "Sony WH-1000XM5",
    price: 399,
    rating: 4.9,
    reviews: 245,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2Eg05QRmQ1oMAgHin4bmvryV7jD5RZ66KTC1ZSfJZyA&s=10",
  },
  {
    id: 4,
    title: "Apple Watch Series 9",
    price: 429,
    rating: 4.7,
    reviews: 156,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfuH8j4ykTk3JbwZJ2ayausaPd5nYdydpL9cCdmKA8Ig&s=10",
  },
  {
    id: 5,
    title: "Canon EOS R50",
    price: 749,
    rating: 4.8,
    reviews: 98,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_Lvm1BRjbkmRFI8BvQzjCp7L6SKMR1-67GSdne4AwoQ&s=10",
  },
  {
    id: 6,
    title: "MacBook Air M3",
    price: 1299,
    rating: 4.9,
    reviews: 310,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg5LCPx0lDncMa0ltyXi_aT7FV1w2bBFkTCxlgj96Uxg&s=10",
  },
  {
    id: 7,
    title: "PlayStation 5",
    price: 499,
    rating: 4.9,
    reviews: 420,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3uDlNclEzmWwHlkh6B4Dqd1Da8hVEJRgq8VYxNISUBUaFft_r3PISfqI&s=10",
  },
  {
    id: 8,
    title: "New Balance 9060",
    price: 189,
    rating: 4.5,
    reviews: 142,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP3QRB_y1AonNqHnM0ZHcxceqK0lSsVVRvQThvgLLHNQ&s=10",
  },
];
export default products;